version: '3'
services:
  node1:
    build: .
    #image: ubuntu:20.04
    command: bash -c "while true; do echo -e \"node 1 is running\"; sleep 2; done"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./:/project
      - /run/nfd:/run/nfd
    networks:
      common-net:
        ipv4_address: 192.168.10.225
    expose:
      - 6363
      - 56363
      - 9696


networks:
  common-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
